database:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/academicdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  user: root
  password: 1234
  
  properties:
    hibernate.current_session_context_class: thread
    hibernate.hbm2ddl.auto: update
    hibernate.dialect: org.hibernate.dialect.MySQLDialect